### ISSUE TITLE
write-policy: support for "Lazy Condition Keys"

### ISSUE THREAD

**Issue by kmcquade** [salesforce/policy_sentry#21]
Just speculating here on how we might implement condition keys support.

There would have to be two separate functions available to users.

1. First, there would have to be a command to list out a table of `service`, `action_name`, `resource_type`, `raw_arn`, and Condition Keys. This way, a user could identify which condition key they would want to include in their policy.

2. Second, there would have to be a way for the user to supply the condition key to the `crud.yml` or `actions.yml`, using something under the current structure. Given that our goal is to abstract the complexity of IAM to the user, we'd want to allow the user to say "I know how condition keys work, but don't feel like determining all the cases where it does or does not apply for specific actions per ARN, so use this condition key wherever possible, and here's the value that I want it to use. 

```yaml
policy_with_crud_levels:
- name: 'PolicyNameWithCRUD'
  description: 'Why I need these privs'
  arn: 'arn:aws:iam::123456789012:role/RiskyEC2'
  read:
    - arn:aws:s3:::example-kinnaird
    - arn:aws:ssm:us-east-1:123456789012:parameter/test
    - arn:aws:kms:us-east-1:123456789012:key/123456
      # Perhaps like this or some other data structure, not sure
      # This will be applied wherever possible, for this specific resource
       condition_key_string: "kms:CallerAccount"
       condition_type_string: "StringEquals"
       condition_value: "123456789012"
  write:
    - arn:aws:kms:us-east-1:123456789012:key/123456
  list:
    - arn:aws:s3:::example-org-sbx-vmimport/stuff
  tag:
    - arn:aws:ssm:us-east-1:123456789012:parameter/test
  permissions-management:
    - arn:aws:secretsmanager:us-east-1:123456789012:secret:mysecret
  # This would be applied wherever possible across all actions
  universal-conditions:
    - condition_key_string: "ec2:ResourceTag/purpose"
       condition_type_string: "StringEquals"
       condition_value: "test"
    # example
    - condition_key_string: "aws:SecureTransport"
      condition_type_string: "Bool"
      condition_value: "True"
```

Notice how in the above yml file, there are two different places where conditions will be valid:
1. The first is under a specific resource within a CRUD level. This will say, "whenever there is an action under Read access level for this specific KMS key, make sure that you use the Condition Key `kms:CallerAccount` with a value of `123456789012`. However, this will not apply to other CRUD/ARN pairs unless otherwise specified
2. The second is under a new dict titled `universal-conditions`. This will say, "wherever we are able to use the condition key `aws:ResourceTag`, set it to `aws:ResourceTag/${TagKey}` with the K/V pair of `TagKey`, `TagValue`.
