### ISSUE TITLE
DynamoDB ARN being misread by Policy Sentry

### ISSUE THREAD

**Issue by kmcquade** [salesforce/policy_sentry#215]
Input:

```yaml
mode: crud
name: ''
# Specify resource ARNs
read:
- 'arn:aws:dynamodb:us-east-1:123456789123:table/mytable'
write:
- 'arn:aws:dynamodb:us-east-1:123456789123:table/mytable'
list:
- 'arn:aws:dynamodb:us-east-1:123456789123:table/mytable'
tagging:
- ''
permissions-management:
- ''
# Actions that do not support resource constraints
wildcard-only:
  single-actions: # standalone actions
  - ''
  # Service-wide - like 's3' or 'ec2'
  service-read:
  - 'dynamodb'
  service-write:
  - ''
  service-list:
  - 'dynamodb'
  service-tagging:
  - ''
  service-permissions-management:
  - ''
# Skip resource constraint requirements by listing actions here.
skip-resource-constraints:
- ''
# Exclude actions from the output by specifying them here. Accepts wildcards, like kms:Delete*
exclude-actions:
- ''
```

Output:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "MultMultNone",
            "Effect": "Allow",
            "Action": [
                "dynamodb:DescribeLimits",
                "dynamodb:DescribeReservedCapacity",
                "dynamodb:DescribeReservedCapacityOfferings",
                "dynamodb:ListStreams",
                "dynamodb:ListBackups",
                "dynamodb:ListContributorInsights",
                "dynamodb:ListGlobalTables",
                "dynamodb:ListTables"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Sid": "DynamodbReadTable",
            "Effect": "Allow",
            "Action": [
                "dynamodb:BatchGetItem",
                "dynamodb:ConditionCheckItem",
                "dynamodb:DescribeContinuousBackups",
                "dynamodb:DescribeContributorInsights",
                "dynamodb:DescribeTable",
                "dynamodb:DescribeTableReplicaAutoScaling",
                "dynamodb:DescribeTimeToLive",
                "dynamodb:GetItem",
                "dynamodb:ListTagsOfResource",
                "dynamodb:Query",
                "dynamodb:Scan"
            ],
            "Resource": [
                "arn:aws:dynamodb:us-east-1:123456789123:table/mytable"
            ]
        },
        {
            "Sid": "DynamodbReadBackup",
            "Effect": "Allow",
            "Action": [
                "dynamodb:DescribeBackup"
            ],
            "Resource": [
                "arn:aws:dynamodb:us-east-1:123456789123:table/mytable"
            ]
        },
        {
            "Sid": "DynamodbReadIndex",
            "Effect": "Allow",
            "Action": [
                "dynamodb:DescribeContributorInsights",
                "dynamodb:Query",
                "dynamodb:Scan"
            ],
            "Resource": [
                "arn:aws:dynamodb:us-east-1:123456789123:table/mytable"
            ]
        },
        {
            "Sid": "DynamodbReadStream",
            "Effect": "Allow",
            "Action": [
                "dynamodb:DescribeStream",
                "dynamodb:GetRecords",
                "dynamodb:GetShardIterator"
            ],
            "Resource": [
                "arn:aws:dynamodb:us-east-1:123456789123:table/mytable"
            ]
        },
        {
            "Sid": "DynamodbWriteTable",
            "Effect": "Allow",
            "Action": [
                "dynamodb:BatchWriteItem",
                "dynamodb:CreateBackup",
                "dynamodb:CreateGlobalTable",
                "dynamodb:CreateTable",
                "dynamodb:CreateTableReplica",
                "dynamodb:DeleteItem",
                "dynamodb:DeleteTable",
                "dynamodb:DeleteTableReplica",
                "dynamodb:PutItem",
                "dynamodb:RestoreTableFromBackup",
                "dynamodb:RestoreTableToPointInTime",
                "dynamodb:UpdateContinuousBackups",
                "dynamodb:UpdateContributorInsights",
                "dynamodb:UpdateGlobalTable",
                "dynamodb:UpdateGlobalTableSettings",
                "dynamodb:UpdateItem",
                "dynamodb:UpdateTable",
                "dynamodb:UpdateTableReplicaAutoScaling",
                "dynamodb:UpdateTimeToLive"
            ],
            "Resource": [
                "arn:aws:dynamodb:us-east-1:123456789123:table/mytable"
            ]
        },
        {
            "Sid": "DynamodbWriteBackup",
            "Effect": "Allow",
            "Action": [
                "dynamodb:DeleteBackup",
                "dynamodb:RestoreTableFromBackup"
            ],
            "Resource": [
                "arn:aws:dynamodb:us-east-1:123456789123:table/mytable"
            ]
        },
        {
            "Sid": "DynamodbWriteIndex",
            "Effect": "Allow",
            "Action": [
                "dynamodb:UpdateContributorInsights"
            ],
            "Resource": [
                "arn:aws:dynamodb:us-east-1:123456789123:table/mytable"
            ]
        }
    ]
}
```

I believe the ARN slicing functions are causing this somehow. Look at the ARN types in the output of `policy_sentry query arn-table --service dynamodb`:

```
arn:${Partition}:dynamodb:${Region}:${Account}:table/${TableName}/index/${IndexName}
arn:${Partition}:dynamodb:${Region}:${Account}:table/${TableName}/stream/${StreamLabel}
arn:${Partition}:dynamodb:${Region}:${Account}:table/${TableName}
arn:${Partition}:dynamodb:${Region}:${Account}:table/${TableName}/backup/${BackupName}
arn:${Partition}:dynamodb::${Account}:global-table/${GlobalTableName}
```

It clearly is not recognizing the difference between `table/${TableName}/index/${IndexName}` and `table/${TableName}`.

Will have to dig into this later.
