### ISSUE TITLE
feature: Controlling access using tags

### ISSUE THREAD

**Issue by shinitiandrei** [salesforce/policy_sentry#388]
Hi there,
Firstly, thanks for providing this amazing tool for the community :).

So, I've been going through your docs and tutorials, but I wasn't able to see anywhere where we can set rules/permissions based on tags, so I believe that is not done yet.
As for https://docs.aws.amazon.com/IAM/latest/UserGuide/access_iam-tags.html, can you guys add this to your backlog and get this feature added? Not sure what it would look like but anything like this would help :)

```
mode: crud
name: 'read-only'
read:
- 'arn:aws:ssm:ap-southeast-2:123456789012:parameter/myparameter'
   tags: 
   - squad: my-squad
```

Thank you very much!
